### PR TITLE
algorithm: Adding  scrypt hashing and tests

### PR DESCRIPTION
**Pull request by trasherdk**
## Description

**Scrypt hashing in NodeJS and Javascript**
Password hashing and compare functions.

### CODE REVIEW

**Comment by fncolon** [comment]
since this repository only accept encryption (not hashing), i will close this pull request, **thanks for your work**, maybe this will help for people doing "scrypt" research later and found this pull request :tada: (i hope you happy about that).

**Comment by trasherdk** [comment]
If I'm not wrong, you'll need a hashing function to do AES encryption. Am I wrong?

Also, you will need a function to calculate/derive a reasonable IV, not only relying on pre-calculated values.

This PR also provides tests that not only demonstrates that functions don't crash, but actually returns what is expected.

People will not be able to find this, after rejection, as I don't keep stale breaches around.

**Comment by fncolon** [comment]
> If I'm not wrong, you'll need a hashing function to do AES encryption. Am I wrong?
> 
> Also, you will need a function to calculate/derive a reasonable IV, not only relying on pre-calculated values.
> 
> This PR also provides tests that not only demonstrates that functions don't crash, but actually returns what is expected.
> 
> People will not be able to find this, after rejection, as I don't keep stale breaches around.

Yes i need hashing function for the secret key but not for the example in the website, provided examples in the website only for encryption.

**Comment by fncolon** [comment]
Also i will not using scrypt for any encryption examples. So i think put it in the repository is out of context.

**Comment by fncolon** [comment]
> If I'm not wrong, you'll need a hashing function to do AES encryption. Am I wrong?
> 
> Also, you will need a function to calculate/derive a reasonable IV, not only relying on pre-calculated values.
> 
> This PR also provides tests that not only demonstrates that functions don't crash, but actually returns what is expected.
> 
> People will not be able to find this, after rejection, as I don't keep stale breaches around.

can you give the reference about "function to calculate/derive a reasonable IV, not only relying in pre-calculated values"? i think current IV is reasonable.

**Comment by trasherdk** [comment]
The IV stuff would have been my next PR. Tests should not rely on pre-calculated values, but go the steps creating those values during each test. That will test the robustness of every step required to perform the actual encryption/decryption.

You can view the scrypt functions as a support to do AES and other stuff.

**Comment by fncolon** [comment]
> The IV stuff would have been my next PR. Tests should not rely on pre-calculated values, but go the steps creating those values during each test. That will test the robustness of every step required to perform the actual encryption/decryption.
> 
> You can view the scrypt functions as a support to do AES and other stuff.

I see, can you remove the test for the scrypt function and use it instead in AES test? 

also for next time maybe you should creating some issue first and give detail about the changes before doing some PR, because it will be confusing if you didn't give any detail and reason in your PR.

**Comment by trasherdk** [comment]
I'm also working on a set of tests that encrypt some text and only pass if the decrypt returns the exact  same text :smiley: 

I don't know where you are at, but I'm at UTC+7 :thailand:

**Comment by fncolon** [comment]
> I'm also working on a set of tests that encrypt some text and only pass if the decrypt returns the exact same text 😃
> 
> I don't know where you are at, but I'm at UTC+7 🇹🇭

it will be a plus.

i'm from UTC+7 🆔

**Comment by trasherdk** [comment]
Because `scrypt.js` is a module by itself, support or not, it should have it's own tests, separate from whatever other functions it is used by. Functions using `scrypt.js` should have tests demonstrating the relationship actually works.

**Comment by fncolon** [comment]
> Because `scrypt.js` is a module by itself, support or not, it should have it's own tests, separate from whatever other functions it is used by. Functions using `scrypt.js` should have tests demonstrating the relationship actually works.

Ok, but implement it in AES instead is better to reduce complexity for future tests. Can you implement the `scrypt` hash in AES test instead of create its own test?

**Review by fncolon — CHANGES_REQUESTED** [review]
remove `scrypt.test.js` and implement the scrypt hashing in AES test instead.

**Comment by fncolon** [comment]
will reopen, close due to unanswered.

**Pull request closed without merging**
