### PR TITLE
Tests/3des

### PR DESCRIPTION
**Pull request by trasherdk**
I accidentally ran `npm test` and that was a mess.

Trying to come up with a fix, I separated the `3des` test.

Running `npm run test:3des` will run tests only on `3des.test.js`

```sh
$ npm run test:3des

> encryptlab@0.3.0 test:3des
> jest tests/3des.test.js

 PASS  tests/3des.test.js
  ✓ is encrypt work? (6 ms)
  ✓ is decrypt work? (4 ms)
  ✓ is encrypt/decrypt what we expect? (7 ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        0.928 s, estimated 1 s
Ran all test suites matching /tests\/3des.test.js/i.
```

### CODE REVIEW

**Comment by fncolon** [comment]
I don't agree with the seperated test solution, `npm run test` alone should be recommended to run all tests.

**Comment by fncolon** [comment]
Can you provide which the mess side? 

Check the test and it's passed but the warning still appearing, can you leave this task to me?

Capture

Will close this PR now, thanks.

**Comment by trasherdk** [comment]
I did the `test:3des` to not have every undhandled reject messages filling up the console.
It makes it more easy to fix one problem at the time.

The test passes, but the test is wrong. Take a look at the test I added.

**Comment by fncolon** [comment]
> I did the `test:3des` to not have every undhandled reject messages filling up the console.
> It makes it more easy to fix one problem at the time.
> 
> The test passes, but the test is wrong. Take a look at the test I added.

Already look at it and it's better just to remove the unhandled reject message that filling up the console.

The test passes when the decrypted value from encrypt is equal so the unit test didn't wrong but there is warning on it, i will corresponding about the warning. Thanks for the insight.

**Comment by fncolon** [comment]
@trasherdk issue solved https://github.com/fncolon/encryptlab/runs/3151210271

**Pull request closed without merging**
